rubocop:
  image_name: codeclimate/codeclimate-rubocop
  image_id: 83380a80e2395a172bf93e64762d3a0cdcd7b8ffc55be99d849119d8de1d3b90
  description: A Ruby static code analyzer, based on the community Ruby style guide.
gofmt:
  image_name: codeclimate/codeclimate-gofmt
  image_id: c8ba52f4645ce0cc134e34cef40eb1335d9ac365d61f72728307687a981f1b64
  description: gofmt
golint:
  image_name: codeclimate/codeclimate-golint
  description: golint
coffeelint:
  image_name: codeclimate/codeclimate-coffeelint
  description: A style checker for CoffeeScript
eslint:
  image_name: codeclimate/codeclimate-eslint
  description: A JavaScript/JSX linting utility
csslint:
  image_name: codeclimate/codeclimate-csslint
  description: Automated linting of Cascading Stylesheets
